-- Ejecutar en SQL*Plus / SQL Developer y pasar el resultado.
SET PAGESIZE 0
SET LINESIZE 300
SET FEEDBACK OFF

-- 1) Tablas con columnas de CUIT, RUCA, CTG, RENSPA, corredor o especie
SELECT TABLE_NAME || ' | ' || COLUMN_NAME || ' | ' || DATA_TYPE
FROM ALL_TAB_COLUMNS
WHERE OWNER = 'SYSADMIN_ELN'
  AND (COLUMN_NAME LIKE '%CUIT%'
    OR COLUMN_NAME LIKE '%RUCA%'
    OR COLUMN_NAME LIKE '%ONCCA%'
    OR COLUMN_NAME LIKE '%CTG%'
    OR COLUMN_NAME LIKE '%RENSPA%'
    OR COLUMN_NAME LIKE '%CORREDOR%'
    OR COLUMN_NAME LIKE '%AFIP%')
ORDER BY TABLE_NAME, COLUMN_NAME;

-- 2) Claves foráneas de INGRESOS_PLANTAS (a qué tabla apunta cada código)
SELECT A.COLUMN_NAME || ' -> ' || PK.TABLE_NAME || '.' || PKC.COLUMN_NAME
FROM ALL_CONSTRAINTS C
JOIN ALL_CONS_COLUMNS A   ON A.OWNER = C.OWNER AND A.CONSTRAINT_NAME = C.CONSTRAINT_NAME
JOIN ALL_CONSTRAINTS PK   ON PK.OWNER = C.R_OWNER AND PK.CONSTRAINT_NAME = C.R_CONSTRAINT_NAME
JOIN ALL_CONS_COLUMNS PKC ON PKC.OWNER = PK.OWNER AND PKC.CONSTRAINT_NAME = PK.CONSTRAINT_NAME
                         AND PKC.POSITION = A.POSITION
WHERE C.OWNER = 'SYSADMIN_ELN'
  AND C.TABLE_NAME = 'INGRESOS_PLANTAS'
  AND C.CONSTRAINT_TYPE = 'R'
ORDER BY A.COLUMN_NAME;

-- 3) Tablas cuyo nombre sugiere CPE, especies, corredores o entidades
SELECT TABLE_NAME
FROM ALL_TABLES
WHERE OWNER = 'SYSADMIN_ELN'
  AND (TABLE_NAME LIKE '%CARTA%' OR TABLE_NAME LIKE '%CPE%'
    OR TABLE_NAME LIKE '%ESPECIE%' OR TABLE_NAME LIKE '%CORREDOR%'
    OR TABLE_NAME LIKE '%ENTIDAD%' OR TABLE_NAME LIKE '%CUENTA%'
    OR TABLE_NAME LIKE '%PRODUCTOR%')
ORDER BY TABLE_NAME;
